import type { Metadata } from 'next';
import '../globals.css';
import Navbar from '@/shared/components/shared/Navbar';

import { AuroraBackground } from '@/shared/components/ui/aurora-background';
import { AuroraMotionWrapper } from '@/shared/components/shared/AuroraMotionWrapper';
import TaskSidebar from '@/shared/components/shared/TaskSideBar';
import { currentUser } from '@clerk/nextjs/server';
import WhoToFollow from '@/shared/components/shared/WhoToFollow';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  if (!user) return null;
  const username = user.username ?? user.emailAddresses[0].emailAddress.split('@')[0];
  return (
    <>
      <Navbar />
      <div className="min-h-screen relative">
        <main className="py-8">
          <div className="max-w-7xl mx-auto px-4 ">
            <div className="flex gap-4">
              {/* Sidebar зліва */}
              <div className="order-2 xs:flex xs:order-1 xs:static fixed bottom-0 left-0 w-full xs:w-auto  z-10">
                <TaskSidebar username={username} />
              </div>

              {/* Контент */}
              <div className="order-1  w-full">
                <AuroraMotionWrapper>{children}</AuroraMotionWrapper>
              </div>

              {/* WhoToFollow справа */}
              {user && (
                <div className="hidden md:block md:order-3">
                  <WhoToFollow />
                </div>
              )}
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
