import type { Metadata } from 'next';
import '../globals.css';

import { AuroraMotionWrapper } from '@/shared/components/shared/AuroraMotionWrapper';
import Navbar from '@/shared/components/shared/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AuroraMotionWrapper>
        <Navbar />
        <div className="min-h-screen relative">
          <AuroraMotionWrapper>{children}</AuroraMotionWrapper>
        </div>
      </AuroraMotionWrapper>
    </>
  );
}
